SELECT E.ID, IFNULL(P.CNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA AS E
LEFT JOIN 
(SELECT PARENT_ID, COUNT(PARENT_ID) AS CNT FROM ECOLI_DATA
WHERE PARENT_ID IS NOT NULL
GROUP BY PARENT_ID) AS P
ON E.ID = P.PARENT_ID