SELECT E.ID,
CASE
    WHEN (D.RANKING=4) THEN 'LOW'
    WHEN (D.RANKING=3) THEN 'MEDIUM'
    WHEN (D.RANKING=2) THEN 'HIGH'
    ELSE 'CRITICAL'
END AS COLONY_NAME
FROM ECOLI_DATA AS E
JOIN (
    SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS RANKING
    FROM ECOLI_DATA
) AS D
ON E.ID = D.ID
ORDER BY ID


