WITH RECURSIVE CTE
AS ( 
    SELECT ID, PARENT_ID, 1 AS N
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL

    SELECT E.ID, E.PARENT_ID, CTE.N+1 AS N
    FROM ECOLI_DATA AS E
    JOIN CTE ON CTE.ID = E.PARENT_ID
)

SELECT COUNT(A.ID) AS 'COUNT', A.N AS GENERATION 
FROM CTE AS A
LEFT JOIN CTE AS B ON A.ID=B.PARENT_ID
WHERE B.ID IS NULL
GROUP BY A.N
ORDER BY A.N