WITH CAR_INFO AS (
    SELECT CAR_ID, SUM(1) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31'
    GROUP BY CAR_ID
)

SELECT CAST(DATE_FORMAT(START_DATE,'%c') AS UNSIGNED) AS MONTH, CAR_ID, SUM(1) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_INFO
    WHERE RECORDS >= 5
) AND START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31'
GROUP BY MONTH, CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC